"""Series_Attributes.is_favourite

Revision ID: 2a47e8031541
Revises: afe08201dbc8
Create Date: 2017-05-03 15:23:34.420014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a47e8031541'
down_revision = 'afe08201dbc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Series_Attributes', sa.Column('is_favourite', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Series_Attributes', 'is_favourite')
    # ### end Alembic commands ###
