"""alert table

Revision ID: afe08201dbc8
Revises: b46043443bf2
Create Date: 2017-04-26 18:10:54.562302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe08201dbc8'
down_revision = 'b46043443bf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Alerts',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('entity_id_fk', sa.Integer(), nullable=False),
                    sa.Column('series_id_fk', sa.Integer(), nullable=False),
                    sa.Column('alert_predicate_type', sa.Enum('data_delay', 'value_too_low', 'value_too_high',
                                                              name='alert_predicate_type'), nullable=False),
                    sa.Column('value', sa.Float(), nullable=False),
                    sa.Column('is_enabled', sa.Boolean(), nullable=False),
                    sa.Column('last_check_status', sa.Boolean(), nullable=True),
                    sa.Column('alert_recipient_email', sa.String(length=255), nullable=True),
                    sa.Column('delete_ts', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['entity_id_fk'], ['Entities.id'], ),
                    sa.ForeignKeyConstraint(['series_id_fk'], ['Series_Attributes.id'], ),
                    sa.PrimaryKeyConstraint('id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Alerts')
    # ### end Alembic commands ###
