"""global metadata - timestamp of last modification

Revision ID: b46043443bf2
Revises: ced76af19eed
Create Date: 2017-03-31 00:11:00.516808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b46043443bf2'
down_revision = 'ced76af19eed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Global_Metadata',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('last_data_modification_ts', sa.Integer(), nullable=False),
                    sa.Column('delete_ts', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Global_Metadata')
    # ### end Alembic commands ###
