"""enum series

Revision ID: ced76af19eed
Revises: 310d770bc073
Create Date: 2017-03-30 23:57:34.262792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ced76af19eed'
down_revision = '310d770bc073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Series_Enum_Values',
                    sa.Column('series_id_fk', sa.Integer(), nullable=False),
                    sa.Column('int_value', sa.Integer(), nullable=False),
                    sa.Column('str_value', sa.String(length=255), nullable=False),
                    sa.ForeignKeyConstraint(['series_id_fk'], ['Series_Attributes.id'], ),
                    sa.PrimaryKeyConstraint('series_id_fk', 'int_value'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Series_Enum_Values')
    # ### end Alembic commands ###
